32 modify sidebar
hammadsi/KP-3 pull request #21
Opened 2023-10-19 13:36 UTC by simeonc01

Completed. 

Another bug dicovered (please check if  it's the case for you too): when loading the patients for the physician a 403 error eccors. Think this has something to do with the API connection?

2023-10-19 16:02 UTC, EmmaPeders1 commented
When I register I am given the role as a physician 👀

2023-10-24 10:58 UTC, anines requested changes
Looks good!

2023-10-24 10:58 UTC, anines commented on kegeland-frontend/src/routes/index.tsx
> +    path: '/patients/:patientId',   // kun fysio
I think comment should either be in our worklanguage English, or be removed

2023-10-24 10:58 UTC, anines commented on kegeland-frontend/src/routes/index.tsx
> +    title: '404',             // begge
Same comment comment, English or remove

2023-10-24 11:23 UTC, simeonc01 commented
Good observation!! Comments are removed.

2023-10-24 11:24 UTC, kentrv commented
LGTM

2023-10-24 11:33 UTC, kentrv approved these changes

2023-10-24 11:35 UTC, simeonc01 commented
> I read all the +228,242 lines of the new code, LGTM. @simeonc01

Thanks, @kentrv !! I thought it became a bit of "spaghetti" code eventually, but since you've gone over every single line and you think it looks good, I'm satisfied :)

2023-10-24 11:53 UTC, anines commented
@simeonc01 Will you resolve merge conflicts as well? All code looks very nice btw, good job!

2023-10-24 12:20 UTC, anines approved these changes

2023-10-24 12:21 UTC, merged